// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package queries

import (
	"context"
)

const getCache = `-- name: GetCache :one
SELECT response FROM cache WHERE hash = ?
`

func (q *Queries) GetCache(ctx context.Context, hash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCache, hash)
	var response string
	err := row.Scan(&response)
	return response, err
}

const setCache = `-- name: SetCache :exec
INSERT INTO cache (hash, response) VALUES (?, ?)
ON CONFLICT(hash) DO UPDATE SET response = excluded.response
`

type SetCacheParams struct {
	Hash     string `json:"hash"`
	Response string `json:"response"`
}

func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.ExecContext(ctx, setCache, arg.Hash, arg.Response)
	return err
}
