// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package queries

import (
	"context"
)

const addHistory = `-- name: AddHistory :one
INSERT INTO history (source_type, source_uri, prompt)
VALUES (?, ?, ?)
RETURNING id, source_type, source_uri, prompt, created_at
`

type AddHistoryParams struct {
	SourceType string `json:"source_type"`
	SourceUri  string `json:"source_uri"`
	Prompt     string `json:"prompt"`
}

func (q *Queries) AddHistory(ctx context.Context, arg AddHistoryParams) (History, error) {
	row := q.db.QueryRowContext(ctx, addHistory, arg.SourceType, arg.SourceUri, arg.Prompt)
	var i History
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceUri,
		&i.Prompt,
		&i.CreatedAt,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, source_type, source_uri, prompt, created_at FROM history ORDER BY created_at DESC
`

func (q *Queries) ListHistory(ctx context.Context) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceUri,
			&i.Prompt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
