// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type Cache struct {
	Hash      string    `json:"hash"`
	Response  string    `json:"response"`
	CreatedAt time.Time `json:"created_at"`
}

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type History struct {
	ID         int64     `json:"id"`
	SourceType string    `json:"source_type"`
	SourceUri  string    `json:"source_uri"`
	Prompt     string    `json:"prompt"`
	CreatedAt  time.Time `json:"created_at"`
}
