// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	AddHistory(ctx context.Context, arg AddHistoryParams) (History, error)
	GetCache(ctx context.Context, hash string) (string, error)
	GetConfig(ctx context.Context, key string) (string, error)
	ListHistory(ctx context.Context) ([]History, error)
	SetCache(ctx context.Context, arg SetCacheParams) error
	SetConfig(ctx context.Context, arg SetConfigParams) error
}

var _ Querier = (*Queries)(nil)
